import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import * as staff from '../controllers/staff-controller.js';
import * as holder from '../controllers/holder-controller.js';
import * as auth from '../controllers/auth-controller.js';
import * as tenant from '../controllers/tenant-controller.js';
import * as templates from '../controllers/template-controller.js';
import * as bulk from '../controllers/bulk-controller.js';
import * as exportsController from '../controllers/export-controller.js';
import * as certificateFiles from '../controllers/certificate-file-controller.js';
import * as publicCertificateFiles from '../controllers/public-certificate-file-controller.js';
import multer from 'multer';
import * as pub from '../controllers/public-controller.js';
import { requireAuth, requireTenant, allowRoles } from '../middleware/auth.js';
import { validate, registerSchema, loginSchema, courseSchema, recipientSchema, certificateSchema, revokeSchema, reissueSchema, templateSchema, recipientUpdateSchema, staffInvitationSchema, acceptInvitationSchema } from '../validators/schemas.js';

const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 1024 * 1024, files: 1, fields: 0 } });
const issueRoles = allowRoles('ORGANIZATION_OWNER', 'ORGANIZATION_ADMIN', 'ORGANIZATION_STAFF');
const publicVerificationLimit = rateLimit({ windowMs: 60_000, limit: 20, standardHeaders: true, legacyHeaders: false, message: { error: { code: 'RATE_LIMITED', message: 'Too many verification attempts. Please wait a minute.' } } });
router.get('/health', pub.health);
router.post('/auth/register', validate(registerSchema), auth.register);
router.post('/auth/login', validate(loginSchema), auth.login);
router.post('/auth/logout', auth.logout);
router.get('/me', requireAuth, auth.me);
router.get('/verify/:certificateId', publicVerificationLimit, pub.verify);
router.get('/certificates/:certificateId/public-file', publicVerificationLimit, publicCertificateFiles.download);
router.post('/staff-invitations/accept', validate(acceptInvitationSchema), staff.accept);
router.get('/holder/certificates', requireAuth, allowRoles('CERTIFICATE_HOLDER'), holder.list);
router.get('/holder/certificates/:id', requireAuth, allowRoles('CERTIFICATE_HOLDER'), holder.detail);
router.use(requireAuth, requireTenant);
router.get('/dashboard', tenant.dashboard);
router.get('/analytics', tenant.analytics);
router.get('/audit-logs', tenant.auditLogs);
router.get('/staff', allowRoles('ORGANIZATION_OWNER'), staff.list);
router.post('/staff/invitations', allowRoles('ORGANIZATION_OWNER'), staff.invite);
router.post('/staff/invitations/:id/revoke', allowRoles('ORGANIZATION_OWNER'), staff.revoke);
router.route('/templates').get(templates.list).post(issueRoles, validate(templateSchema), templates.create);
router.patch('/templates/:id', issueRoles, validate(templateSchema), templates.update);
router.post('/templates/:id/duplicate', issueRoles, templates.duplicate);
router.delete('/templates/:id', issueRoles, templates.remove);
router.route('/courses').get(tenant.listCourses).post(issueRoles, validate(courseSchema), tenant.createCourse);
router.route('/recipients').get(tenant.listRecipients).post(issueRoles, validate(recipientSchema), tenant.createRecipient);
router.route('/recipients/:id').get(tenant.getRecipient).patch(issueRoles, validate(recipientUpdateSchema), tenant.updateRecipient);
router.post('/certificates/bulk', issueRoles, upload.single('file'), bulk.issue);
router.post('/certificates/bulk/error-report', issueRoles, bulk.errorReport);
router.get('/certificates/export', issueRoles, exportsController.certificates);
router.get('/recipients/export', issueRoles, exportsController.recipients);
router.get('/verifications/export', issueRoles, exportsController.verifications);
router.route('/certificates').get(tenant.listCertificates).post(issueRoles, validate(certificateSchema), tenant.createCertificate);
router.get('/certificates/:id/file', issueRoles, certificateFiles.download);
router.get('/certificates/:id', tenant.getCertificate);
router.post('/certificates/:id/revoke', issueRoles, validate(revokeSchema), tenant.revoke);
router.post('/certificates/:id/reissue', issueRoles, validate(reissueSchema), tenant.reissue);
export default router;
